export const START_LOADING_UPDATE_DATA = 'START_LOADING_UPDATE_DATA';
export const LOADING_UPDATE_DATA_SUCCESS = 'SUCCESS_LOADING_UPDATE_DATA';
export const LOADING_UPDATE_DATA_ERROR = 'ERROR_LOADING_UPDATE_DATA';

export const GET_GRANTS = 'GET_GRANTS';

