export const START_LOADING_UPDATE_DATA = 'START_LOADING_UPDATE_DATA';
export const LOADING_UPDATE_DATA_SUCCESS = 'SUCCESS_LOADING_UPDATE_DATA';
export const LOADING_UPDATE_DATA_ERROR = 'ERROR_LOADING_UPDATE_DATA';

export const GET_GRANTS = 'GET_GRANTS';

export const START_LOADING_GRANTS = 'START_LOADING_GRANTS';
export const LOADING_GRANTS_SUCCESS = 'LOADING_GRANTS_SUCCESS';
export const LOADING_GRANTS_ERROR = 'LOADING_GRANTS_ERROR';

